"""The torch column of `laya_onnx/README.md`'s latency tables, checked in.

`bench_latency.py` measures the ONNX path and refuses to let torch into the process (item 4 of
its docstring: a latency measured beside a resident torch is not the one a deployment gets).
That is the right rule for the ONNX column, and it left the torch column with no script behind
it -- the README's same-machine comparison was a recorded off-tree run. This module is that
run, so the comparison can be regenerated by anyone with the weights.

It reuses `STATE`, `questions()` and `measure()` from `bench_latency` unchanged, so the two
columns are the same state, the same questions in the same order, and the same warmup/timed
protocol and the same nearest-rank percentiles. Importing `bench_latency` is cheap and
torch-free; the torch import is this file's own, which `laya_onnx/bench/__init__.py` permits
for `bench/` and forbids one directory up.

Two processes, never one. Run this and `bench_latency` separately and line the tables up by
hand; a single process that timed both would let whichever library initialised first shape the
other's thread pool.

`--threads` sets `torch.set_num_threads`, the counterpart of `bench_latency --threads`
(onnxruntime's `intra_op_num_threads`). Pinning both to the same small number is how the
README's 4-thread table was made: on the 80-way host that table was measured on, each
library's *default* pool is the number a two-socket box gives it, not the number a commodity
container would, and the two defaults are not even the same size.

Weights come through `laya.load`, i.e. the Hub cache, exactly as the torch path itself loads
them; no evaluation data is fetched, which keeps `bench/`'s no-fetch rule intact.

Run it:

    python -m laya_onnx.bench.bench_torch --threads 4 --counts 1,5,10 --runs 20 --warmup 3
    python -m laya_onnx.bench.bench_torch                # torch's default thread count
"""
import argparse
import os

_SUMMARY = "Wall-clock latency of laya.Agent.system_one (torch, CPU), by questions per call."

os.environ.setdefault("USE_TF", "0")
os.environ.setdefault("USE_TORCH", "1")
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")

from .bench_latency import STATE, measure, questions  # noqa: E402


def main(argv=None) -> int:
    # `_SUMMARY` rather than `__doc__` for the same reason as bench_latency: `__doc__` is None
    # under `python -OO`.
    ap = argparse.ArgumentParser(description=_SUMMARY)
    ap.add_argument("--model", default="convaiinnovations/laya",
                    help="Hub repo id or local checkpoint dir (default convaiinnovations/laya)")
    ap.add_argument("--subfolder", default="multilingual",
                    help="checkpoint subfolder inside --model (default multilingual, the one the ONNX export is of)")
    ap.add_argument("--runs", type=int, default=50, help="timed runs per question count (default 50)")
    ap.add_argument("--warmup", type=int, default=5, help="discarded runs per question count (default 5)")
    ap.add_argument("--threads", type=int, default=None,
                    help="torch.set_num_threads; default leaves torch's own default, which on a large "
                         "host is every physical core")
    ap.add_argument("--counts", default="1,5,10,50", help="comma-separated questions-per-call (default 1,5,10,50)")
    args = ap.parse_args(argv)

    import torch  # imported here so --help works without torch installed

    if args.threads is not None:
        torch.set_num_threads(int(args.threads))

    import laya  # noqa: E402  (imports torch; fine in bench/, see its __init__)

    # device="cpu" on purpose: the ONNX artifact is fp32, and laya picks fp32 on cpu but the
    # checkpoint's bf16 amp dtype on cuda. A torch column measured in bf16 on a GPU would not
    # be the comparison the README makes.
    agent = laya.load(args.model, subfolder=args.subfolder or None, device="cpu")
    counts = [int(c) for c in args.counts.split(",") if c.strip()]

    print("model     : %s%s" % (args.model, ("/" + args.subfolder) if args.subfolder else ""))
    print("torch     : %s, threads=%d" % (torch.__version__, torch.get_num_threads()))
    print()
    print("%10s %10s %10s %10s %10s" % ("questions", "p50 ms", "p95 ms", "min ms", "max ms"))
    for n in counts:
        r = measure(agent, STATE, questions(n), runs=args.runs, warmup=args.warmup)
        print("%10d %10.1f %10.1f %10.1f %10.1f"
              % (r["n_questions"], r["p50_ms"], r["p95_ms"], r["min_ms"], r["max_ms"]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
